<?php
/**
 * Aaho Extension
 *
 * @category   Aaho
 * @package    Aaho_Account
 * @author     Ashok Kumar Mishra <ashokmishra.cpp@gmail.com>
 */
$tables = $this->getTables();
?>
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }
</style>
<div class="Restaurant">
    <table>
        <tr>
            <th>Table</th>
            <th>Items</th>
            <th>Price</th>
        </tr>
		<?php $totalPrice = 0; ?>
        <?php foreach ($tables as $table): ?>
			<?php $totalPrice += $table['price']; ?>
			<tr>
				<td><?php echo $table['table_no'] ?></td>
				<td><?php echo $table['items'] ?></td>
				<td><?php echo $table['price'] ?></td>
			</tr>
        <?php endforeach; ?>
		<tr>
			<td>Total</td>
			<td></td>
			<td><?php echo $totalPrice ?></td>
		</tr>
    </table>
</div>

<script>
    setTimeout(function () { location.reload(1); }, 1000);
</script>